"""Hatchling build hook that embeds the git commit date and compiles the C extensions.

Writes ``src/jamma/_build_meta.py`` at build time so the release date is
available at runtime via ``jamma.__release_date__`` without manual upkeep.

Also compiles three C extensions if a C compiler is available:
  - ``src/jamma/lmm/_lmm_accel.c``: per-SNP REML Wald pipeline (with OpenMP)
  - ``src/jamma/lmm/_eigen_accel.c``: DSYEVR eigendecomposition (no OpenMP)
  - ``src/jamma/lmm/_secular_accel.c``: DLAED4 rank-1 secular updates (no OpenMP)

If compilation fails for any reason, a warning is logged and a pure-Python
wheel is produced as a graceful fallback — jamma is fully functional without
either C extension.
"""

import datetime
import os
import platform
import shutil
import subprocess
import sys
import sysconfig
from pathlib import Path

from hatchling.builders.hooks.plugin.interface import BuildHookInterface


class CustomBuildHook(BuildHookInterface):
    def initialize(self, version, build_data):
        # Write _build_meta.py with the git commit date
        try:
            date_str = subprocess.check_output(
                ["git", "log", "-1", "--format=%ci"],
                text=True,
                stderr=subprocess.DEVNULL,
            ).strip()[:10]
        except (FileNotFoundError, subprocess.CalledProcessError):
            date_str = datetime.date.today().isoformat()

        meta_path = Path(self.root) / "src" / "jamma" / "_build_meta.py"
        meta_path.write_text(
            f'"""Auto-generated by hatch_build.py - do not edit."""\n\n'
            f'BUILD_DATE = "{date_str}"\n'
        )

        # Compile C extensions (graceful fallback if unavailable).
        # _lmm_accel is more critical — compile first so its errors are visible.
        self._compile_c_extension(build_data)
        self._compile_eigen_extension(build_data)
        self._compile_secular_extension(build_data)

    def _preflight_c_build(self):
        """Verify build prerequisites and return compiler/include information.

        Checks that numpy >= 2.0 is available, the C compiler is on PATH,
        and Python.h exists. All checks produce actionable WARNING messages
        on failure.

        Returns:
            tuple(cc_cmd, cc_extra, python_inc, numpy_inc, ldflags) on success,
            or None if any pre-flight check fails.
        """
        try:
            import numpy as np
        except ImportError:
            print(
                "WARNING: numpy not available in build environment — "
                "skipping C extension compilation (pure-Python fallback).",
                file=sys.stderr,
            )
            return None

        # Refuse to compile against numpy 1.x — the resulting .so crashes on
        # numpy 2.x at import time due to C API ABI break (NPY_ABI_VERSION).
        np_major = int(np.__version__.split(".")[0])
        if np_major < 2:
            print(
                f"WARNING: build numpy is {np.__version__} (1.x) — "
                "skipping C extension to avoid ABI mismatch with numpy 2.x "
                "at runtime (pure-Python fallback).\n"
                "  To compile the C extension, build with numpy >= 2.0:\n"
                "    pip install --no-build-isolation --no-deps jamma",
                file=sys.stderr,
            )
            return None

        # Resolve compiler — CC may contain flags (e.g. "gcc -pthread")
        cc = os.environ.get("CC") or sysconfig.get_config_var("CC") or "cc"
        cc_parts = cc.split()
        cc_cmd = cc_parts[0]
        cc_extra = cc_parts[1:]

        # Pre-flight: verify compiler is on PATH
        if not shutil.which(cc_cmd):
            print(
                f"WARNING: C compiler '{cc_cmd}' not found on PATH — "
                "skipping C extension compilation (pure-Python fallback).\n"
                "  To enable the C extension, install a C compiler:\n"
                "    Debian/Ubuntu: apt-get install -y gcc\n"
                "    macOS: xcode-select --install",
                file=sys.stderr,
            )
            return None

        python_inc = sysconfig.get_config_var("INCLUDEPY")
        numpy_inc = np.get_include()

        # Pre-flight: verify Python.h exists (python3-dev package)
        python_h = Path(python_inc) / "Python.h" if python_inc else None
        if not python_h or not python_h.exists():
            print(
                f"WARNING: Python.h not found at {python_inc} — "
                "skipping C extension compilation (pure-Python fallback).\n"
                "  To enable the C extension, install Python development headers:\n"
                "    Debian/Ubuntu: apt-get install -y python3-dev\n"
                "    Fedora/RHEL: dnf install python3-devel",
                file=sys.stderr,
            )
            return None

        # macOS requires -undefined dynamic_lookup for Python C extensions
        # (Python symbols are resolved at runtime from the embedding binary)
        ldflags = []
        if platform.system() == "Darwin":
            ldflags = ["-undefined", "dynamic_lookup"]

        return (cc_cmd, cc_extra, python_inc, numpy_inc, ldflags)

    def _detect_linux_openmp_flags(self, cc_cmd: str) -> list[str]:
        """Detect the best OpenMP flags for Linux.

        Prefers Intel OpenMP (libiomp5) when available to avoid the
        libgomp/libiomp5 dual-runtime conflict on systems with MKL-backed
        numpy. Falls back to GNU OpenMP (-fopenmp → libgomp).

        Args:
            cc_cmd: C compiler command name.

        Returns:
            Compiler flags for OpenMP.
        """
        try:
            import numpy as np

            np_dir = Path(np.__file__).parent
            for d in [
                np_dir / ".libs",
                np_dir.parent / "numpy.libs",
                np_dir / "_core" / ".libs",
            ]:
                if not d.is_dir():
                    continue
                for lib in d.iterdir():
                    if "libiomp5" in lib.name and ".so" in lib.name:
                        print(
                            f"Intel OpenMP found: {lib}",
                            file=sys.stderr,
                        )
                        return [
                            f"-L{d}",
                            "-liomp5",
                            f"-Wl,-rpath,{d}",
                            "-fopenmp",
                        ]
        except ImportError:
            pass

        # Check system-wide libiomp5
        result = subprocess.run(
            [cc_cmd, "-liomp5", "-x", "c", "-", "-o", "/dev/null"],
            input="int main(){return 0;}\n",
            capture_output=True,
            text=True,
        )
        if result.returncode == 0:
            print("Intel OpenMP (system libiomp5) detected", file=sys.stderr)
            return ["-liomp5", "-fopenmp"]

        return ["-fopenmp"]

    def _compile_c_extension(self, build_data):
        """Compile _lmm_accel.c -> _lmm_accel{EXT_SUFFIX} if a C compiler is available.

        Uses sysconfig to locate Python headers and numpy to locate its include
        directory. OpenMP support is attempted:
          - macOS: -Xpreprocessor -fopenmp via Homebrew libomp
          - Linux: -fopenmp (GCC/Clang)

        On any compilation failure, logs a warning and returns without raising.
        The compiled .so is written to src/jamma/lmm/ where hatchling's normal
        package discovery picks it up automatically for wheel inclusion.

        Args:
            build_data: Hatchling build data dict. Updated with force_include
                entry mapping the compiled .so into the wheel.
        """
        preflight = self._preflight_c_build()
        if preflight is None:
            return
        cc_cmd, cc_extra, python_inc, numpy_inc, ldflags = preflight

        src = Path(self.root) / "src" / "jamma" / "lmm" / "_lmm_accel.c"
        if not src.exists():
            print(
                f"WARNING: C source {src} not found — skipping C extension "
                "compilation (pure-Python fallback). If building from sdist, "
                "verify the archive is complete.",
                file=sys.stderr,
            )
            return

        ext_suffix = sysconfig.get_config_var("EXT_SUFFIX") or ".so"
        out_name = f"_lmm_accel{ext_suffix}"
        out_path = Path(self.root) / "src" / "jamma" / "lmm" / out_name

        # Platform-specific OpenMP flags
        omp_flags = []
        if platform.system() == "Darwin":
            try:
                prefix = subprocess.check_output(
                    ["brew", "--prefix", "libomp"],
                    text=True,
                    stderr=subprocess.DEVNULL,
                ).strip()
                omp_flags = [
                    f"-I{prefix}/include",
                    f"-L{prefix}/lib",
                    "-Xpreprocessor",
                    "-fopenmp",
                    "-lomp",
                ]
            except (FileNotFoundError, subprocess.CalledProcessError):
                # No Homebrew libomp — compile single-threaded C (still faster
                # than Python loops; _OPENMP is undefined so #pragma is skipped)
                print(
                    "OpenMP not available on macOS (libomp not found). "
                    "C extension will be single-threaded.",
                    file=sys.stderr,
                )
        else:
            omp_flags = self._detect_linux_openmp_flags(cc_cmd)

        # Respect CFLAGS for arch-specific builds (e.g. -march=x86-64-v3)
        extra_cflags = os.environ.get("CFLAGS", "").split()

        cmd = [
            cc_cmd,
            *cc_extra,
            "-O3",
            "-ftree-vectorize",
            "-fno-math-errno",
            "-fno-trapping-math",
            "-funroll-loops",
            *extra_cflags,
            "-fno-finite-math-only",  # override -Ofast in CFLAGS; isnan() must work
            "-fPIC",
            "-shared",
            "-std=c11",
            f"-I{python_inc}",
            f"-I{numpy_inc}",
            *omp_flags,
            str(src),
            "-o",
            str(out_path),
            "-lm",
            *ldflags,
        ]

        result = subprocess.run(cmd, capture_output=True, text=True)
        if result.returncode != 0:
            if omp_flags:
                # Retry without OpenMP — libgomp may not be installed
                cmd_no_omp = [x for x in cmd if x not in omp_flags]
                print(
                    "OpenMP compilation failed, retrying without OpenMP "
                    "(single-threaded C extension)...",
                    file=sys.stderr,
                )
                result2 = subprocess.run(cmd_no_omp, capture_output=True, text=True)
                if result2.returncode == 0:
                    print(
                        f"C extension compiled (single-threaded): {out_path}",
                        file=sys.stderr,
                    )
                    build_data.setdefault("force_include", {})
                    dist_path = f"jamma/lmm/{out_name}"
                    build_data["force_include"][str(out_path)] = dist_path
                    build_data["pure_python"] = False
                    build_data["infer_tag"] = True
                    return
                # Both attempts failed — show both errors for diagnostics
                print(
                    "WARNING: C extension compilation failed "
                    "(pure-Python fallback will be used):\n"
                    f"  OpenMP command: {' '.join(cmd)}\n"
                    f"  OpenMP error: {result.stderr[:1000]}\n"
                    f"  No-OpenMP command: {' '.join(cmd_no_omp)}\n"
                    f"  No-OpenMP error: {result2.stderr[:1000]}",
                    file=sys.stderr,
                )
                return
            print(
                "WARNING: C extension compilation failed "
                "(pure-Python fallback will be used):\n"
                f"  Command: {' '.join(cmd)}\n"
                f"  Error: {result.stderr[:2000]}",
                file=sys.stderr,
            )
            return

        print(f"C extension compiled: {out_path}", file=sys.stderr)

        # Register the compiled .so as a forced wheel inclusion.
        # force_include maps: absolute_source_path -> distribution_path
        # distribution_path is relative to the package root within the wheel,
        # e.g. "jamma/lmm/_lmm_accel.cpython-311-darwin.so"
        build_data.setdefault("force_include", {})
        dist_path = f"jamma/lmm/{out_name}"
        build_data["force_include"][str(out_path)] = dist_path

        # Tell hatchling this is a platform wheel (not pure-Python).
        # Without this, the wheel gets tagged py3-none-any even though it
        # contains a compiled .so, and cibuildwheel rejects it.
        # infer_tag makes hatchling use the current platform/ABI for the
        # wheel filename tag (e.g. cp311-cp311-macosx_14_0_arm64).
        build_data["pure_python"] = False
        build_data["infer_tag"] = True

    def _compile_eigen_extension(self, build_data):
        """Compile _eigen_accel.c -> _eigen_accel{EXT_SUFFIX} if compiler is available.

        No OpenMP flags — DSYEVR is a single LAPACK call; MKL/OpenBLAS handles
        threading internally.

        No LAPACK link flags — the extension discovers LAPACK at runtime via
        dlopen (resolves dsyevr_64_ or dsyevr_ from numpy's bundled BLAS).
        This makes the compiled .so portable across numpy builds and eliminates
        auditwheel issues on Linux.

        On any compilation failure, logs a warning and returns without raising.

        Args:
            build_data: Hatchling build data dict. Updated with force_include
                entry mapping the compiled .so into the wheel.
        """
        preflight = self._preflight_c_build()
        if preflight is None:
            return
        cc_cmd, cc_extra, python_inc, numpy_inc, ldflags = preflight

        src = Path(self.root) / "src" / "jamma" / "lmm" / "_eigen_accel.c"
        if not src.exists():
            print(
                f"WARNING: C source {src} not found — skipping eigen C extension "
                "compilation (pure-Python fallback). If building from sdist, "
                "verify the archive is complete.",
                file=sys.stderr,
            )
            return

        ext_suffix = sysconfig.get_config_var("EXT_SUFFIX") or ".so"
        out_name = f"_eigen_accel{ext_suffix}"
        out_path = Path(self.root) / "src" / "jamma" / "lmm" / out_name

        # dlopen needs -ldl on Linux (macOS has dlopen in libSystem)
        dl_flags = ["-ldl"] if platform.system() == "Linux" else []

        # Respect CFLAGS for arch-specific builds (e.g. -march=x86-64-v3)
        extra_cflags = os.environ.get("CFLAGS", "").split()

        cmd = [
            cc_cmd,
            *cc_extra,
            "-O3",
            "-ftree-vectorize",
            "-fno-math-errno",
            "-fno-trapping-math",
            *extra_cflags,
            "-fno-finite-math-only",  # override -Ofast in CFLAGS
            "-fPIC",
            "-shared",
            "-std=c99",
            f"-I{python_inc}",
            f"-I{numpy_inc}",
            str(src),
            "-o",
            str(out_path),
            "-lm",
            *dl_flags,
            *ldflags,
        ]

        result = subprocess.run(cmd, capture_output=True, text=True)
        if result.returncode != 0:
            print(
                "WARNING: eigen C extension compilation failed "
                "(pure-Python fallback will be used):\n"
                f"  Command: {' '.join(cmd)}\n"
                f"  Error: {result.stderr[:2000]}",
                file=sys.stderr,
            )
            return

        print(f"Eigen C extension compiled: {out_path}", file=sys.stderr)

        # Register the compiled .so as a forced wheel inclusion.
        build_data.setdefault("force_include", {})
        dist_path = f"jamma/lmm/{out_name}"
        build_data["force_include"][str(out_path)] = dist_path

        # pure_python and infer_tag may already be set by _compile_c_extension.
        # Set them unconditionally — idempotent (same values).
        build_data["pure_python"] = False
        build_data["infer_tag"] = True

    def _compile_secular_extension(self, build_data):
        """Compile _secular_accel.c -> _secular_accel{EXT_SUFFIX}.

        No OpenMP flags — DLAED4 calls are sequential (each needs its own workspace).
        No LAPACK link flags — resolves dlaed4_64_ or dlaed4_ at runtime via dlopen.

        On any compilation failure, logs a warning and returns without raising.

        Args:
            build_data: Hatchling build data dict. Updated with force_include
                entry mapping the compiled .so into the wheel.
        """
        preflight = self._preflight_c_build()
        if preflight is None:
            return
        cc_cmd, cc_extra, python_inc, numpy_inc, ldflags = preflight

        src = Path(self.root) / "src" / "jamma" / "lmm" / "_secular_accel.c"
        if not src.exists():
            print(
                f"WARNING: C source {src} not found — skipping secular C extension "
                "compilation (pure-Python fallback). If building from sdist, "
                "verify the archive is complete.",
                file=sys.stderr,
            )
            return

        ext_suffix = sysconfig.get_config_var("EXT_SUFFIX") or ".so"
        out_name = f"_secular_accel{ext_suffix}"
        out_path = Path(self.root) / "src" / "jamma" / "lmm" / out_name

        # dlopen needs -ldl on Linux (macOS has dlopen in libSystem)
        dl_flags = ["-ldl"] if platform.system() == "Linux" else []

        # Respect CFLAGS for arch-specific builds (e.g. -march=x86-64-v3)
        extra_cflags = os.environ.get("CFLAGS", "").split()

        cmd = [
            cc_cmd,
            *cc_extra,
            "-O3",
            "-ftree-vectorize",
            "-fno-math-errno",
            "-fno-trapping-math",
            *extra_cflags,
            "-fno-finite-math-only",  # override -Ofast in CFLAGS
            "-fPIC",
            "-shared",
            "-std=c99",
            f"-I{python_inc}",
            f"-I{numpy_inc}",
            str(src),
            "-o",
            str(out_path),
            "-lm",
            *dl_flags,
            *ldflags,
        ]

        result = subprocess.run(cmd, capture_output=True, text=True)
        if result.returncode != 0:
            print(
                "WARNING: secular C extension compilation failed "
                "(pure-Python fallback will be used):\n"
                f"  Command: {' '.join(cmd)}\n"
                f"  Error: {result.stderr[:2000]}",
                file=sys.stderr,
            )
            return

        print(f"Secular C extension compiled: {out_path}", file=sys.stderr)

        build_data.setdefault("force_include", {})
        dist_path = f"jamma/lmm/{out_name}"
        build_data["force_include"][str(out_path)] = dist_path

        build_data["pure_python"] = False
        build_data["infer_tag"] = True
