"""Hatchling build hook that embeds the git commit date and compiles the C extensions.

Writes ``src/jamma/_build_meta.py`` at build time so the release date is
available at runtime via ``jamma.__release_date__`` without manual upkeep.

Also compiles two C extensions if a C compiler is available:
  - ``src/jamma/lmm/_lmm_accel.c``: per-SNP REML Wald pipeline (with OpenMP)
  - ``src/jamma/jlinalg/src/*.c``: jlinalg BLAS compute layer (with OpenMP)

If compilation fails for any reason, a warning is logged and a pure-Python
wheel is produced as a graceful fallback — jamma is fully functional without
either C extension.
"""

import datetime
import os
import platform
import shutil
import subprocess
import sys
import sysconfig
import tempfile
import urllib.request
from pathlib import Path

from hatchling.builders.hooks.plugin.interface import BuildHookInterface

# BLIS prebuilt binary repository and asset naming convention.
# The BLIS repo ships ILP64 binaries (built with -b 64 -i 64).
# BLIS uses same symbol names (dgemm_, cblas_dgemm) but with 64-bit int args.
# blas_dispatch.c detects ILP64 via bli_info_get_int_type_size().
BLIS_REPO = "michael-denyer/blis-prebuilt"
BLIS_VERSION = "v0.2.0"
BLIS_ASSETS = {
    ("Linux", "x86_64"): "libblis-x86_64.so",  # haswell config
    ("Linux", "AMD64"): "libblis-x86_64.so",  # alias
    ("Darwin", "arm64"): "libblis-firestorm.dylib",  # Apple Silicon
    # Intel Mac: no BLIS binary — Accelerate provides ILP64 via $NEWLAPACK$ILP64
}


class CustomBuildHook(BuildHookInterface):
    def initialize(self, version, build_data):
        # Write _build_meta.py with the git commit date
        try:
            date_str = subprocess.check_output(
                ["git", "log", "-1", "--format=%ci"],
                text=True,
                stderr=subprocess.DEVNULL,
            ).strip()[:10]
        except (FileNotFoundError, subprocess.CalledProcessError):
            date_str = datetime.date.today().isoformat()

        meta_path = Path(self.root) / "src" / "jamma" / "_build_meta.py"
        meta_path.write_text(
            f'"""Auto-generated by hatch_build.py - do not edit."""\n\n'
            f'BUILD_DATE = "{date_str}"\n'
        )

        # Compile C extensions (graceful fallback if unavailable).
        # _lmm_accel is more critical — compile first so its errors are visible.
        self._compile_c_extension(build_data)
        self._compile_jlinalg_extension(build_data)

    def _preflight_c_build(self):
        """Verify build prerequisites and return compiler/include information.

        Checks that numpy >= 2.0 is available, the C compiler is on PATH,
        and Python.h exists. All checks produce actionable WARNING messages
        on failure.

        Returns:
            tuple(cc_cmd, cc_extra, python_inc, numpy_inc, ldflags) on success,
            or None if any pre-flight check fails.
        """
        try:
            import numpy as np
        except ImportError:
            print(
                "WARNING: numpy not available in build environment — "
                "skipping C extension compilation (pure-Python fallback).",
                file=sys.stderr,
            )
            return None

        # Refuse to compile against numpy 1.x — the resulting .so crashes on
        # numpy 2.x at import time due to C API ABI break (NPY_ABI_VERSION).
        np_major = int(np.__version__.split(".")[0])
        if np_major < 2:
            print(
                f"WARNING: build numpy is {np.__version__} (1.x) — "
                "skipping C extension to avoid ABI mismatch with numpy 2.x "
                "at runtime (pure-Python fallback).\n"
                "  To compile the C extension, build with numpy >= 2.0:\n"
                "    pip install --no-build-isolation --no-deps jamma",
                file=sys.stderr,
            )
            return None

        # Resolve compiler — CC may contain flags (e.g. "gcc -pthread")
        cc = os.environ.get("CC") or sysconfig.get_config_var("CC") or "cc"
        cc_parts = cc.split()
        cc_cmd = cc_parts[0]
        cc_extra = cc_parts[1:]

        # Pre-flight: verify compiler is on PATH
        if not shutil.which(cc_cmd):
            print(
                f"WARNING: C compiler '{cc_cmd}' not found on PATH — "
                "skipping C extension compilation (pure-Python fallback).\n"
                "  To enable the C extension, install a C compiler:\n"
                "    Debian/Ubuntu: apt-get install -y gcc\n"
                "    macOS: xcode-select --install",
                file=sys.stderr,
            )
            return None

        python_inc = sysconfig.get_config_var("INCLUDEPY")
        numpy_inc = np.get_include()

        # Pre-flight: verify Python.h exists (python3-dev package)
        python_h = Path(python_inc) / "Python.h" if python_inc else None
        if not python_h or not python_h.exists():
            print(
                f"WARNING: Python.h not found at {python_inc} — "
                "skipping C extension compilation (pure-Python fallback).\n"
                "  To enable the C extension, install Python development headers:\n"
                "    Debian/Ubuntu: apt-get install -y python3-dev\n"
                "    Fedora/RHEL: dnf install python3-devel",
                file=sys.stderr,
            )
            return None

        # macOS requires -undefined dynamic_lookup for Python C extensions
        # (Python symbols are resolved at runtime from the embedding binary)
        ldflags = []
        if platform.system() == "Darwin":
            ldflags = ["-undefined", "dynamic_lookup"]

        return (cc_cmd, cc_extra, python_inc, numpy_inc, ldflags)

    def _fetch_blis_binary(self, build_data) -> Path | None:
        """Fetch a prebuilt BLIS shared library from GitHub Release assets.

        Checks for a pre-downloaded binary via JLINALG_BLIS_PATH env var first,
        then attempts to download from the BLIS prebuilt repo. Returns None
        (non-fatal) if the binary cannot be obtained.

        Set JLINALG_SKIP_BLIS=1 to skip BLIS entirely (e.g. on Linux CI where
        the prebuilt .so targets a newer glibc than manylinux_2_28 allows).

        Args:
            build_data: Hatchling build data dict (unused, kept for API symmetry).

        Returns:
            Path to the BLIS binary, or None if unavailable.
        """
        if os.environ.get("JLINALG_SKIP_BLIS", "").strip() == "1":
            print(
                "JLINALG_SKIP_BLIS=1 — skipping BLIS bundling.",
                file=sys.stderr,
            )
            return None

        # Allow CI to provide a pre-downloaded binary
        env_path = os.environ.get("JLINALG_BLIS_PATH")
        if env_path:
            blis = Path(env_path)
            if blis.is_file():
                print(f"Using pre-downloaded BLIS: {blis}", file=sys.stderr)
                return blis
            print(
                f"WARNING: JLINALG_BLIS_PATH={env_path} does not exist — "
                "falling back to download.",
                file=sys.stderr,
            )

        key = (platform.system(), platform.machine())
        asset_name = BLIS_ASSETS.get(key)
        if asset_name is None:
            print(
                f"WARNING: No BLIS binary available for platform {key} — "
                "jlinalg own dgemm will be used.",
                file=sys.stderr,
            )
            return None

        libs_dir = Path(self.root) / "src" / "jamma" / "jlinalg" / "libs"
        target = libs_dir / asset_name

        # Skip download if already present (repeated builds)
        if target.is_file():
            print(f"BLIS binary already present: {target}", file=sys.stderr)
            return target

        url = (
            f"https://github.com/{BLIS_REPO}/releases/download/"
            f"{BLIS_VERSION}/{asset_name}"
        )
        libs_dir.mkdir(parents=True, exist_ok=True)

        try:
            print(f"Downloading BLIS from {url} ...", file=sys.stderr)
            urllib.request.urlretrieve(url, target)
            print(f"BLIS downloaded: {target}", file=sys.stderr)
            return target
        except Exception as exc:
            print(
                f"WARNING: BLIS download failed ({exc}) — "
                "jlinalg own dgemm will be used.",
                file=sys.stderr,
            )
            # Clean up partial download
            if target.exists():
                target.unlink()
            return None

    def _bundle_blis(self, build_data) -> None:
        """Fetch and bundle BLIS shared library into the wheel.

        On macOS, sets @loader_path install_name to prevent delocate from
        moving the dylib to .dylibs/ (which would break blas_dispatch.c's
        dlopen path).

        Args:
            build_data: Hatchling build data dict. Updated with force_include
                if BLIS binary is available.
        """
        blis_path = self._fetch_blis_binary(build_data)
        if blis_path is None:
            print(
                "BLIS not bundled (jlinalg own dgemm will be used).",
                file=sys.stderr,
            )
            return

        # macOS: set @loader_path install_name so delocate leaves it in place.
        # blas_dispatch.c expects BLIS at <extension_dir>/libs/libblis.dylib.
        if platform.system() == "Darwin" and blis_path.suffix == ".dylib":
            install_name = "@loader_path/libs/libblis.dylib"
            try:
                subprocess.run(
                    ["install_name_tool", "-id", install_name, str(blis_path)],
                    capture_output=True,
                    text=True,
                    check=True,
                )
                print(
                    f"Set BLIS install_name to {install_name}",
                    file=sys.stderr,
                )
            except Exception as exc:
                print(
                    f"WARNING: install_name_tool failed ({exc}) — "
                    "delocate may move the dylib.",
                    file=sys.stderr,
                )

        # Register BLIS binary for wheel inclusion.
        # Use generic name (libblis.so / libblis.dylib) so that
        # blas_dispatch.c's discover_bundled_blis() can find it at runtime
        # regardless of the platform-specific asset name.
        build_data.setdefault("force_include", {})
        generic_name = (
            "libblis.dylib" if platform.system() == "Darwin" else "libblis.so"
        )
        dist_path = f"jamma/jlinalg/libs/{generic_name}"
        build_data["force_include"][str(blis_path)] = dist_path
        print(
            f"BLIS bundled: {blis_path} -> {dist_path}",
            file=sys.stderr,
        )

    def _detect_linux_openmp_flags(self, cc_cmd: str) -> tuple[list[str], list[str]]:
        """Detect the best OpenMP flags for Linux.

        Prefers Intel OpenMP (libiomp5) when available to avoid the
        libgomp/libiomp5 dual-runtime conflict on systems with MKL-backed
        numpy. Falls back to GNU OpenMP (-fopenmp → libgomp).

        On GCC, ``-fopenmp`` at link time implicitly adds ``-lgomp``.  When
        we link libiomp5 by full path, passing ``-fopenmp`` to the linker
        would load *both* libgomp and libiomp5 — triggering an Intel OMP
        assertion failure (``kmp_runtime.cpp``).

        Args:
            cc_cmd: C compiler command name.

        Returns:
            ``(compile_flags, link_flags)`` for OpenMP.
        """
        try:
            import numpy as np

            np_dir = Path(np.__file__).parent
            for d in [
                np_dir / ".libs",
                np_dir.parent / "numpy.libs",
                np_dir / "_core" / ".libs",
            ]:
                if not d.is_dir():
                    continue
                for lib in d.iterdir():
                    if "libiomp5" in lib.name and ".so" in lib.name:
                        print(
                            f"Intel OpenMP found: {lib}",
                            file=sys.stderr,
                        )
                        # Link by full path — numpy bundles versioned names
                        # like libiomp5-2f035e84.so with no unversioned
                        # symlink, so -liomp5 fails at link time.  Do NOT
                        # pass -fopenmp to the linker: GCC would add
                        # -lgomp, creating a dual OpenMP runtime.
                        return (
                            ["-fopenmp"],
                            [str(lib), f"-Wl,-rpath,{d}"],
                        )
        except ImportError:
            pass

        # Check system-wide libiomp5
        result = subprocess.run(
            [cc_cmd, "-liomp5", "-x", "c", "-", "-o", "/dev/null"],
            input="int main(){return 0;}\n",
            capture_output=True,
            text=True,
        )
        if result.returncode == 0:
            print("Intel OpenMP (system libiomp5) detected", file=sys.stderr)
            return (["-fopenmp"], ["-liomp5"])

        return (["-fopenmp"], ["-fopenmp"])

    def _compile_c_extension(self, build_data):
        """Compile _lmm_accel.c -> _lmm_accel{EXT_SUFFIX} if a C compiler is available.

        Uses sysconfig to locate Python headers and numpy to locate its include
        directory. OpenMP support is attempted:
          - macOS: -Xpreprocessor -fopenmp via Homebrew libomp
          - Linux: -fopenmp (GCC/Clang)

        On any compilation failure, logs a warning and returns without raising.
        The compiled .so is written to src/jamma/lmm/ where hatchling's normal
        package discovery picks it up automatically for wheel inclusion.

        Args:
            build_data: Hatchling build data dict. Updated with force_include
                entry mapping the compiled .so into the wheel.
        """
        preflight = self._preflight_c_build()
        if preflight is None:
            return
        cc_cmd, cc_extra, python_inc, numpy_inc, ldflags = preflight

        src = Path(self.root) / "src" / "jamma" / "lmm" / "_lmm_accel.c"
        if not src.exists():
            print(
                f"WARNING: C source {src} not found — skipping C extension "
                "compilation (pure-Python fallback). If building from sdist, "
                "verify the archive is complete.",
                file=sys.stderr,
            )
            return

        ext_suffix = sysconfig.get_config_var("EXT_SUFFIX") or ".so"
        out_name = f"_lmm_accel{ext_suffix}"
        out_path = Path(self.root) / "src" / "jamma" / "lmm" / out_name

        # Platform-specific OpenMP flags — split compile/link to avoid
        # loading both libgomp (-fopenmp on GCC linker) and libiomp5 (MKL).
        omp_compile: list[str] = []
        omp_link: list[str] = []
        if platform.system() == "Darwin":
            try:
                prefix = subprocess.check_output(
                    ["brew", "--prefix", "libomp"],
                    text=True,
                    stderr=subprocess.DEVNULL,
                ).strip()
                if Path(prefix, "lib").is_dir():
                    omp_compile = [
                        f"-I{prefix}/include",
                        "-Xpreprocessor",
                        "-fopenmp",
                    ]
                    omp_link = [
                        f"-L{prefix}/lib",
                        "-lomp",
                    ]
                else:
                    print(
                        f"OpenMP: Homebrew prefix {prefix} exists but lib/ not found. "
                        "C extension will be single-threaded.",
                        file=sys.stderr,
                    )
            except (FileNotFoundError, subprocess.CalledProcessError):
                # No Homebrew libomp — compile single-threaded C (still faster
                # than Python loops; _OPENMP is undefined so #pragma is skipped)
                print(
                    "OpenMP not available on macOS (libomp not found). "
                    "C extension will be single-threaded.",
                    file=sys.stderr,
                )
        else:
            omp_compile, omp_link = self._detect_linux_openmp_flags(cc_cmd)

        # Respect CFLAGS for arch-specific builds (e.g. -march=x86-64-v3)
        extra_cflags = os.environ.get("CFLAGS", "").split()

        # Two-step compile+link to prevent dual OpenMP runtime.
        # GCC's -fopenmp implicitly adds -lgomp at link time. When libiomp5
        # (Intel OpenMP, bundled with MKL numpy) is also linked, both runtimes
        # initialize and abort: "OMP: Error #13: Assertion failure at
        # kmp_runtime.cpp". Splitting into compile (.o) then link (.so) lets
        # us pass -fopenmp only to the compiler and link only libiomp5.
        obj_path = out_path.with_suffix(".o")

        compile_cmd = [
            cc_cmd,
            *cc_extra,
            "-O3",
            "-ftree-vectorize",
            "-fno-math-errno",
            "-fno-trapping-math",
            "-funroll-loops",
            *extra_cflags,
            "-fno-finite-math-only",  # override -Ofast in CFLAGS; isnan() must work
            "-fPIC",
            "-std=c11",
            f"-I{python_inc}",
            f"-I{numpy_inc}",
            *omp_compile,
            "-c",
            str(src),
            "-o",
            str(obj_path),
        ]

        result = subprocess.run(compile_cmd, capture_output=True, text=True)
        if result.returncode != 0:
            if omp_compile:
                # Retry without OpenMP — libgomp may not be installed
                compile_cmd_no_omp = [x for x in compile_cmd if x not in omp_compile]
                print(
                    "OpenMP compilation failed, retrying without OpenMP "
                    "(single-threaded C extension)...",
                    file=sys.stderr,
                )
                result2 = subprocess.run(
                    compile_cmd_no_omp, capture_output=True, text=True
                )
                if result2.returncode == 0:
                    omp_link = []  # Don't link OpenMP if compile failed
                else:
                    print(
                        "WARNING: C extension compilation failed "
                        "(pure-Python fallback will be used):\n"
                        f"  OpenMP error: {result.stderr[:1000]}\n"
                        f"  No-OpenMP error: {result2.stderr[:1000]}",
                        file=sys.stderr,
                    )
                    obj_path.unlink(missing_ok=True)
                    return
            else:
                print(
                    "WARNING: C extension compilation failed "
                    "(pure-Python fallback will be used):\n"
                    f"  Command: {' '.join(compile_cmd)}\n"
                    f"  Error: {result.stderr[:2000]}",
                    file=sys.stderr,
                )
                return

        # Link step: .o -> .so (no -fopenmp here — only libiomp5 link flags)
        link_cmd = [
            cc_cmd,
            "-shared",
            str(obj_path),
            "-o",
            str(out_path),
            *omp_link,
            "-lm",
            *ldflags,
        ]

        result = subprocess.run(link_cmd, capture_output=True, text=True)
        obj_path.unlink(missing_ok=True)  # Clean up .o regardless
        if result.returncode != 0:
            print(
                "WARNING: C extension link failed "
                "(pure-Python fallback will be used):\n"
                f"  Command: {' '.join(link_cmd)}\n"
                f"  Error: {result.stderr[:2000]}",
                file=sys.stderr,
            )
            return

        print(f"C extension compiled: {out_path}", file=sys.stderr)

        # Register the compiled .so as a forced wheel inclusion.
        # force_include maps: absolute_source_path -> distribution_path
        # distribution_path is relative to the package root within the wheel,
        # e.g. "jamma/lmm/_lmm_accel.cpython-311-darwin.so"
        build_data.setdefault("force_include", {})
        dist_path = f"jamma/lmm/{out_name}"
        build_data["force_include"][str(out_path)] = dist_path

        # Tell hatchling this is a platform wheel (not pure-Python).
        # Without this, the wheel gets tagged py3-none-any even though it
        # contains a compiled .so, and cibuildwheel rejects it.
        # infer_tag makes hatchling use the current platform/ABI for the
        # wheel filename tag (e.g. cp311-cp311-macosx_14_0_arm64).
        build_data["pure_python"] = False
        build_data["infer_tag"] = True

    def _compile_jlinalg_extension(self, build_data):
        """Compile jlinalg C sources -> _jlinalg{EXT_SUFFIX}.

        Per-file compile-then-link.

        Compiles each C source file in src/jamma/jlinalg/src/ individually to a
        temporary object file, then links them into a single shared library.
        This enables per-file compiler flag groups (e.g. AVX2 files vs LAPACK files
        with distinct flag sets in future phases).

        OpenMP support is attempted:
          - macOS: -Xpreprocessor -fopenmp via Homebrew libomp
          - Linux: -fopenmp (libgomp or libiomp5 auto-detected)

        On any compilation failure, logs a warning and returns without raising.
        The compiled .so is written to src/jamma/jlinalg/.

        Args:
            build_data: Hatchling build data dict. Updated with force_include
                entry mapping the compiled .so into the wheel.
        """
        preflight = self._preflight_c_build()
        if preflight is None:
            return
        cc_cmd, cc_extra, python_inc, numpy_inc, ldflags = preflight

        jlinalg_src = Path(self.root) / "src" / "jamma" / "jlinalg" / "src"
        jlinalg_inc = Path(self.root) / "src" / "jamma" / "jlinalg" / "include"

        if not jlinalg_src.is_dir():
            print(
                f"WARNING: jlinalg source directory {jlinalg_src} not found — "
                "skipping jlinalg C extension compilation (NumPy fallback).",
                file=sys.stderr,
            )
            return

        # jlinalg source files split into three groups:
        # - baseline: portable C compiled without SIMD flags (runs on any x86_64)
        # - simd: files using AVX2 intrinsics, compiled with -mavx2 -mfma
        # - kernels: ISA-specific microkernel files (required on target platform)
        # This ensures the baseline manylinux_x86_64 wheel doesn't SIGILL on
        # older CPUs that lack AVX2.  Runtime CPUID dispatch in platform.c
        # selects the appropriate kernels.
        baseline_sources = [
            jlinalg_src / "platform.c",
            jlinalg_src / "blas_dispatch.c",
            jlinalg_src / "dnrm2.c",
            jlinalg_src / "dgemv.c",
            jlinalg_src / "pymodule.c",
            jlinalg_src / "dgemm.c",  # blocking framework
            jlinalg_src / "dgemm_generic.c",  # generic scalar microkernel
            jlinalg_src / "dsyrk.c",  # symmetric rank-k update
            jlinalg_src / "dsyr2k.c",  # symmetric rank-2k update
            jlinalg_src / "snp_stats.c",  # single-pass SNP statistics
        ]
        simd_sources = [
            jlinalg_src / "ddot.c",
            jlinalg_src / "daxpy.c",
            jlinalg_src / "dscal.c",
        ]
        # LAPACK sources: strict IEEE 754 required for secular equation deflation.
        # Compiled with -O2 only — MUST NOT get -ffast-math, -Ofast,
        # -ffinite-math-only, or -funroll-loops.
        lapack_sources = [
            jlinalg_src / "dsytrd.c",
            jlinalg_src / "dstedc.c",
            jlinalg_src / "dormtr.c",
            jlinalg_src / "eigh.c",
        ]

        # Kernel directory — required on the matching platform, optional elsewhere.
        jlinalg_kernels = Path(self.root) / "src" / "jamma" / "jlinalg" / "kernels"
        avx2_kernel_sources: list[Path] = []
        neon_kernel_sources: list[Path] = []
        machine = platform.machine()
        if jlinalg_kernels.is_dir():
            avx2_src = jlinalg_kernels / "dgemm_avx2.c"
            neon_src = jlinalg_kernels / "dgemm_neon.c"
            if avx2_src.exists():
                avx2_kernel_sources.append(avx2_src)
            elif machine in ("x86_64", "AMD64"):
                raise SystemExit(
                    f"ERROR: AVX2 dgemm kernel required on "
                    f"{machine} but not found at {avx2_src}"
                )
            if neon_src.exists():
                neon_kernel_sources.append(neon_src)
            elif machine in ("aarch64", "arm64"):
                raise SystemExit(
                    f"ERROR: NEON dgemm kernel required on "
                    f"{machine} but not found at {neon_src}"
                )

        source_files = (
            baseline_sources
            + simd_sources
            + avx2_kernel_sources
            + neon_kernel_sources
            + lapack_sources
        )

        # Only fail on missing baseline + simd + lapack sources; kernels checked above
        missing = [
            s
            for s in (baseline_sources + simd_sources + lapack_sources)
            if not s.exists()
        ]
        if missing:
            print(
                f"WARNING: jlinalg source files missing: {missing} — "
                "skipping jlinalg C extension compilation (NumPy fallback).",
                file=sys.stderr,
            )
            return

        # On x86_64: AVX2/FMA flags are applied only to simd_sources (ddot.c,
        # daxpy.c, dscal.c).  Baseline sources (platform.c, pymodule.c, etc.)
        # are compiled without SIMD flags so the wheel runs on any x86_64 CPU.
        machine = platform.machine()
        simd_flags: list[str] = []
        if machine in ("x86_64", "AMD64"):
            simd_flags = ["-mavx2", "-mfma"]

        # Platform-specific OpenMP flags — split compile/link to avoid
        # loading both libgomp (-fopenmp on GCC linker) and libiomp5 (MKL).
        omp_compile: list[str] = []
        omp_link: list[str] = []
        if platform.system() == "Darwin":
            try:
                prefix = subprocess.check_output(
                    ["brew", "--prefix", "libomp"],
                    text=True,
                    stderr=subprocess.DEVNULL,
                ).strip()
                if Path(prefix, "lib").is_dir():
                    omp_compile = [
                        f"-I{prefix}/include",
                        "-Xpreprocessor",
                        "-fopenmp",
                    ]
                    omp_link = [
                        f"-L{prefix}/lib",
                        "-lomp",
                    ]
                else:
                    print(
                        f"OpenMP: Homebrew prefix {prefix} exists but lib/ not found. "
                        "jlinalg C extension will be single-threaded.",
                        file=sys.stderr,
                    )
            except (FileNotFoundError, subprocess.CalledProcessError):
                print(
                    "OpenMP not available on macOS (libomp not found). "
                    "jlinalg C extension will be single-threaded.",
                    file=sys.stderr,
                )
        else:
            omp_compile, omp_link = self._detect_linux_openmp_flags(cc_cmd)

        # Respect CFLAGS for arch-specific builds (e.g. -march=x86-64-v3)
        extra_cflags = os.environ.get("CFLAGS", "").split()

        # Base compile flags shared by all source files (no SIMD flags here)
        base_cflags = [
            "-O3",
            "-ftree-vectorize",
            "-fno-math-errno",
            "-fno-trapping-math",
            "-funroll-loops",
            *extra_cflags,
            "-fno-finite-math-only",  # override -Ofast; isnan() must work
            "-fPIC",
            "-std=c11",
            f"-I{python_inc}",
            f"-I{numpy_inc}",
            f"-I{jlinalg_inc}",
        ]

        ext_suffix = sysconfig.get_config_var("EXT_SUFFIX") or ".so"
        out_name = f"_jlinalg{ext_suffix}"
        out_path = Path(self.root) / "src" / "jamma" / "jlinalg" / out_name

        # Compile each source file to a .o in a temporary directory
        tmp_dir = Path(tempfile.mkdtemp(prefix="jlinalg_build_"))
        obj_files: list[Path] = []
        compile_failed = False
        use_omp = bool(omp_compile)

        simd_source_set = set(str(s) for s in simd_sources)
        avx2_kernel_set = set(str(s) for s in avx2_kernel_sources)
        lapack_source_set = set(str(s) for s in lapack_sources)

        # Strict IEEE 754 flags for LAPACK sources (secular equation deflation
        # uses infinity arithmetic that -ffast-math breaks).
        lapack_cflags = [
            "-O2",
            "-fno-fast-math",
            "-fno-finite-math-only",
            "-fPIC",
            "-std=c11",
            f"-I{python_inc}",
            f"-I{numpy_inc}",
            f"-I{jlinalg_inc}",
        ]

        def _jlinalg_compile_cmd(
            src: Path,
            obj_file: Path,
            omp_compile_flags: list[str],
        ) -> list[str]:
            """Build the compile command for a single jlinalg source file.

            LAPACK sources get strict IEEE 754 flags (no -ffast-math).
            SIMD/AVX2 sources get -mavx2 -mfma. Baseline sources get base_cflags.

            Args:
                src: Source file path.
                obj_file: Output object file path.
                omp_compile_flags: OpenMP compile-only flags (empty to disable).

            Returns:
                Compiler command as a list of strings.
            """
            if str(src) in lapack_source_set:
                return [
                    cc_cmd,
                    *cc_extra,
                    *lapack_cflags,
                    *omp_compile_flags,
                    "-c",
                    str(src),
                    "-o",
                    str(obj_file),
                ]
            # SIMD sources (ddot, daxpy, dscal) and AVX2 kernel files get
            # -mavx2 -mfma; NEON kernel files get no extra flags (NEON is
            # baseline on aarch64); baseline sources get no SIMD flags.
            extra_simd = (
                simd_flags
                if (str(src) in simd_source_set or str(src) in avx2_kernel_set)
                else []
            )
            return [
                cc_cmd,
                *cc_extra,
                *base_cflags,
                *extra_simd,
                *omp_compile_flags,
                "-c",
                str(src),
                "-o",
                str(obj_file),
            ]

        try:
            for src in source_files:
                obj_file = tmp_dir / (src.stem + ".o")
                cmd_compile = _jlinalg_compile_cmd(src, obj_file, omp_compile)
                # Print compile command to stderr for build-log assertions (CI grep)
                print(f"jlinalg compile: {' '.join(cmd_compile)}", file=sys.stderr)
                result = subprocess.run(cmd_compile, capture_output=True, text=True)
                if result.returncode != 0:
                    print(
                        f"jlinalg compile failed on {src.name}:",
                        file=sys.stderr,
                    )
                    if result.stderr:
                        print(result.stderr, file=sys.stderr)
                    compile_failed = True
                    break
                obj_files.append(obj_file)

            if compile_failed and use_omp:
                # Retry without OpenMP compile flags
                print(
                    "jlinalg OpenMP compilation failed, retrying without OpenMP...",
                    file=sys.stderr,
                )
                obj_files.clear()
                compile_failed = False
                for src in source_files:
                    obj_file = tmp_dir / (src.stem + "_noomp.o")
                    cmd_compile = _jlinalg_compile_cmd(src, obj_file, [])
                    print(
                        f"jlinalg compile (no OMP): {' '.join(cmd_compile)}",
                        file=sys.stderr,
                    )
                    result = subprocess.run(cmd_compile, capture_output=True, text=True)
                    if result.returncode != 0:
                        print(
                            "WARNING: jlinalg C extension compilation failed on "
                            f"{src.name} (NumPy fallback will be used):\n"
                            f"  Error: {result.stderr[:1000]}",
                            file=sys.stderr,
                        )
                        compile_failed = True
                        break
                    obj_files.append(obj_file)
                # No OMP runtime to link if compile retry dropped OMP flags
                omp_link = []

            if compile_failed:
                print(
                    "WARNING: jlinalg C extension compilation failed "
                    "(NumPy fallback will be used).",
                    file=sys.stderr,
                )
                return

            # dlopen/dlsym in blas_dispatch.c needs -ldl on Linux
            dl_flags = ["-ldl"] if platform.system() == "Linux" else []

            # Link all object files into the shared library
            cmd_link = [
                cc_cmd,
                *cc_extra,
                "-shared",
                "-fPIC",
                *[str(o) for o in obj_files],
                "-o",
                str(out_path),
                "-lm",
                *dl_flags,
                *omp_link,
                *ldflags,
            ]
            print(f"jlinalg link: {' '.join(cmd_link)}", file=sys.stderr)
            result_link = subprocess.run(cmd_link, capture_output=True, text=True)
            if result_link.returncode != 0:
                print(
                    "WARNING: jlinalg C extension link failed "
                    "(NumPy fallback will be used):\n"
                    f"  Command: {' '.join(cmd_link)}\n"
                    f"  Error: {result_link.stderr[:2000]}",
                    file=sys.stderr,
                )
                return

        finally:
            # Clean up temporary object files
            shutil.rmtree(tmp_dir, ignore_errors=True)

        print(f"jlinalg C extension compiled: {out_path}", file=sys.stderr)

        # Register the compiled .so for wheel inclusion
        build_data.setdefault("force_include", {})
        build_data["force_include"][str(out_path)] = f"jamma/jlinalg/{out_name}"
        build_data["pure_python"] = False
        build_data["infer_tag"] = True

        # Bundle BLIS shared library (independent of jlinalg .so compilation)
        self._bundle_blis(build_data)
