#!/usr/bin/env python3
"""Regenerate docker/requirements-container.txt from uv.lock and the MKL pins.

Run from the repository root:

    uv run python docker/generate-requirements.py

The runtime section is derived from `uv.lock` so it cannot drift from the
resolution the test suite runs against. The MKL section is not in `uv.lock` at
all: those wheels come from the custom ILP64 index and JAMMA never imports them
directly, so they are declared here and checked by hand against the index.

`uv export` emits a universal resolution: Windows-only packages carry markers,
and `numpy` forks across the 3.11/3.12 boundary. The image is linux/amd64 on
CPython 3.11, and its `numpy` comes from the ILP64 index rather than PyPI, so
both get filtered out here.
"""

from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TARGET = ROOT / "docker" / "requirements-container.txt"

# Intel runtime wheels for MKL-backed ILP64 NumPy. Absent from uv.lock because
# they are transitive dependencies of the ILP64 `numpy` wheel on the custom
# index, not of the `numpy` on PyPI that uv resolves. `mkl` declares
# `onemkl-license`, `intel-openmp`, and `tbb`; the rest follow from those.
MKL_PINS = (
    "mkl==2026.1.0",
    "onemkl-license==2026.1.0",
    "intel-openmp==2026.1.1",
    "intel-cmplr-lib-ur==2026.1.1",
    "umf==1.1.0",
    "tbb==2023.1.0",
    "tcmlib==1.5.0",
)

# Installed separately from the ILP64 index, so it must not appear here.
EXCLUDED_FROM_LOCK = frozenset({"numpy"})

HEADER = """\
# Generated by docker/generate-requirements.py. Do not edit by hand.
#
# The runtime pins below the MKL block come from uv.lock, so the image runs the
# same versions the test suite resolves. Regenerate after any lockfile change:
#
#     uv run python docker/generate-requirements.py
#
# JAMMA and the ILP64 NumPy wheel are installed separately (see the Dockerfile)
# so this file can use the default PyPI index safely.
"""


def runtime_pins_from_lock() -> list[str]:
    """Return the linux/CPython-3.11 runtime pins recorded in uv.lock."""
    exported = subprocess.run(
        [
            "uv",
            "export",
            "--no-dev",
            "--no-emit-project",
            "--no-hashes",
            "--no-annotate",
            "--no-header",
        ],
        cwd=ROOT,
        capture_output=True,
        text=True,
        check=True,
    ).stdout

    pins = []
    for line in exported.splitlines():
        entry = line.strip()
        if not entry or entry.startswith("#"):
            continue
        requirement, _, marker = entry.partition(";")
        if "win32" in marker:
            continue
        requirement = requirement.strip()
        name = re.split(r"[=<>!~\[]", requirement, maxsplit=1)[0]
        if name in EXCLUDED_FROM_LOCK:
            continue
        pins.append(requirement)
    return sorted(pins)


def render() -> str:
    """Return the full text of the container requirements file."""
    lines = [HEADER, *MKL_PINS, *runtime_pins_from_lock()]
    return "\n".join(lines) + "\n"


def main() -> int:
    rendered = render()
    if "--check" in sys.argv:
        current = TARGET.read_text() if TARGET.is_file() else ""
        if current != rendered:
            print(
                f"{TARGET.relative_to(ROOT)} is stale. "
                "Regenerate with: uv run python docker/generate-requirements.py",
                file=sys.stderr,
            )
            return 1
        print(f"{TARGET.relative_to(ROOT)} matches uv.lock")
        return 0

    TARGET.write_text(rendered)
    print(f"Wrote {TARGET.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
