#!/usr/bin/env python3
"""Verify ``tests/fixtures/MANIFEST.toml`` matches the on-disk fixtures.

The GEMMA reference fixtures in ``tests/fixtures/`` are the load-bearing
parity baseline for JAMMA. They were generated from specific GEMMA binary
versions with specific commands; silent edits or bit-rot would invalidate
every parity assertion downstream.

This gate hashes every git-tracked fixture file under ``tests/fixtures/``
and compares against the recorded SHA-256s in ``MANIFEST.toml``. It fails
on:

* Hash mismatch (file edited after manifest generation)
* File present on disk but missing from manifest (untracked addition)
* File in manifest but missing from disk

To intentionally update fixtures: regenerate them, then run
``python scripts/check_fixture_manifest.py --write`` to rebuild the manifest,
and commit both the new fixture files and the manifest in the same commit.
``--write`` preserves any hand-curated ``gemma_version`` / ``generation_cmd``
metadata already recorded for a file, and auto-extracts both from a fixture
whose header carries a ``## GEMMA Version = X.Y`` line.

Usage::

    python scripts/check_fixture_manifest.py         # check
    python scripts/check_fixture_manifest.py --list  # show all tracked files
    python scripts/check_fixture_manifest.py --write # rebuild MANIFEST.toml
"""

from __future__ import annotations

import hashlib
import re
import subprocess
import sys
import tomllib
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
FIXTURES_DIR = REPO_ROOT / "tests" / "fixtures"
MANIFEST_PATH = FIXTURES_DIR / "MANIFEST.toml"
REGENERATE_CMD = "python scripts/check_fixture_manifest.py --write"

GEMMA_VERSION_RE = re.compile(r"##\s*GEMMA Version\s*=\s*(\S+)")
GEMMA_CMD_RE = re.compile(r"##\s*Command Line Input\s*=\s*(.+?)$", re.MULTILINE)


def sha256_of(path: Path) -> str:
    """Stream-hash a file in 1 MiB chunks (works for large fixtures)."""
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def tracked_fixtures() -> list[Path]:
    """Return git-tracked files under ``tests/fixtures/`` (excluding the manifest)."""
    result = subprocess.run(
        ["git", "ls-files", "tests/fixtures/"],
        capture_output=True,
        text=True,
        check=True,
        cwd=REPO_ROOT,
    )
    paths: list[Path] = []
    for line in result.stdout.splitlines():
        rel = line.strip()
        if not rel or rel.endswith("MANIFEST.toml"):
            continue
        paths.append(REPO_ROOT / rel)
    return sorted(paths)


def load_manifest() -> dict[str, dict[str, str]]:
    """Return ``{relative_path: {sha256, ...}}`` from MANIFEST.toml."""
    if not MANIFEST_PATH.exists():
        return {}
    with MANIFEST_PATH.open("rb") as f:
        data = tomllib.load(f)
    return data.get("file", {})


def _extract_gemma_metadata(path: Path) -> dict[str, str]:
    """Parse a fixture file's header for embedded GEMMA metadata.

    Returns ``{"gemma_version": "...", "generation_cmd": "..."}`` for the
    fields that could be extracted; missing fields are simply omitted.
    Only the first ~4 KB are scanned (GEMMA headers are short).
    """
    if not path.is_file():
        return {}
    try:
        head = path.open("rb").read(4096).decode("utf-8", errors="replace")
    except OSError:
        return {}
    out: dict[str, str] = {}
    if (m := GEMMA_VERSION_RE.search(head)) is not None:
        out["gemma_version"] = m.group(1)
    if (m := GEMMA_CMD_RE.search(head)) is not None:
        out["generation_cmd"] = m.group(1).strip()
    return out


def _toml_escape(s: str) -> str:
    """Minimal TOML basic-string escape (sufficient for our paths and shell cmds)."""
    return s.replace("\\", "\\\\").replace('"', '\\"')


def write_manifest() -> int:
    """Rebuild MANIFEST.toml from the tracked fixtures, keeping curated metadata."""
    existing = load_manifest()
    paths = tracked_fixtures()

    lines: list[str] = [
        "# tests/fixtures/MANIFEST.toml",
        "#",
        "# SHA-256 manifest of the GEMMA parity reference fixtures.",
        f"# Auto-generated by {REGENERATE_CMD}.",
        "# Verified by scripts/check_fixture_manifest.py (pre-commit hook).",
        "#",
        "# To intentionally update: regenerate fixtures, run the --write",
        "# command above, commit MANIFEST.toml together with the new files.",
        "",
    ]

    for path in paths:
        rel = path.relative_to(REPO_ROOT).as_posix()
        sha = sha256_of(path)
        meta = _extract_gemma_metadata(path)
        prev = existing.get(rel, {})
        for k in ("gemma_version", "generation_cmd"):
            if k in prev and k not in meta:
                meta[k] = prev[k]

        lines.append(f'[file."{_toml_escape(rel)}"]')
        lines.append(f'sha256 = "{sha}"')
        for k, v in sorted(meta.items()):
            lines.append(f'{k} = "{_toml_escape(v)}"')
        lines.append("")

    FIXTURES_DIR.mkdir(parents=True, exist_ok=True)
    MANIFEST_PATH.write_text("\n".join(lines))
    print(
        f"Wrote {MANIFEST_PATH.relative_to(REPO_ROOT)} "
        f"with {len(paths)} fixture entries."
    )
    return 0


def main(argv: list[str]) -> int:
    if "--write" in argv:
        return write_manifest()
    if "--list" in argv:
        for p in tracked_fixtures():
            print(p.relative_to(REPO_ROOT))
        return 0

    manifest = load_manifest()
    if not manifest:
        sys.stderr.write(
            f"FAIL: {MANIFEST_PATH.relative_to(REPO_ROOT)} is missing or empty.\n"
            f"Run `{REGENERATE_CMD}` to create it.\n"
        )
        return 1

    on_disk = {p.relative_to(REPO_ROOT).as_posix(): p for p in tracked_fixtures()}

    failures: list[str] = []

    # Manifest entries that no longer exist on disk.
    for rel in manifest:
        if rel not in on_disk:
            failures.append(f"  - {rel}: in manifest but not in tests/fixtures/")

    # On-disk files missing from the manifest.
    for rel in on_disk:
        if rel not in manifest:
            failures.append(f"  + {rel}: on disk but absent from manifest")

    # Hash mismatches.
    for rel, path in on_disk.items():
        if rel not in manifest:
            continue
        expected = manifest[rel].get("sha256", "")
        actual = sha256_of(path)
        if expected != actual:
            failures.append(
                f"  ! {rel}: sha256 drift\n"
                f"      expected={expected}\n"
                f"      actual  ={actual}"
            )

    if failures:
        sys.stderr.write(
            "Fixture manifest check FAILED.\n\n" + "\n".join(failures) + "\n\n"
            "If you intentionally regenerated fixtures, run:\n"
            f"    {REGENERATE_CMD}\n"
            "and commit the updated MANIFEST.toml together with the new files.\n"
        )
        return 1

    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
