#!/usr/bin/env python3
"""Rebuild ``tests/fixtures/MANIFEST.toml`` from on-disk fixtures.

Hashes every git-tracked file under ``tests/fixtures/`` and rewrites the
manifest, preserving any human-curated metadata (``gemma_version``,
``generation_cmd``) that was already present for a given file. Use after
intentionally regenerating GEMMA reference fixtures.

For files whose ``.log.txt`` or ``.assoc.txt`` sibling embeds a
``## GEMMA Version = X.Y`` line, that version is auto-extracted into the
manifest entry. Other metadata fields can be hand-edited in MANIFEST.toml
afterward and will survive subsequent regenerations.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

# Re-use sha256_of and tracked_fixtures from the checker so both scripts
# enumerate the same files via ``git ls-files``.
sys.path.insert(0, str(Path(__file__).resolve().parent))
from check_fixture_manifest import (
    FIXTURES_DIR,
    MANIFEST_PATH,
    REPO_ROOT,
    load_manifest,
    sha256_of,
    tracked_fixtures,
)

GEMMA_VERSION_RE = re.compile(r"##\s*GEMMA Version\s*=\s*(\S+)")
GEMMA_CMD_RE = re.compile(r"##\s*Command Line Input\s*=\s*(.+?)$", re.MULTILINE)


def _extract_gemma_metadata(path: Path) -> dict[str, str]:
    """Parse a fixture file's header for embedded GEMMA metadata.

    Returns ``{"gemma_version": "...", "generation_cmd": "..."}`` for the
    fields that could be extracted; missing fields are simply omitted.
    Only the first ~4 KB are scanned (GEMMA headers are short).
    """
    if not path.is_file():
        return {}
    try:
        head = path.open("rb").read(4096).decode("utf-8", errors="replace")
    except OSError:
        return {}
    out: dict[str, str] = {}
    if (m := GEMMA_VERSION_RE.search(head)) is not None:
        out["gemma_version"] = m.group(1)
    if (m := GEMMA_CMD_RE.search(head)) is not None:
        out["generation_cmd"] = m.group(1).strip()
    return out


def _toml_escape(s: str) -> str:
    """Minimal TOML basic-string escape (sufficient for our paths and shell cmds)."""
    return s.replace("\\", "\\\\").replace('"', '\\"')


def main() -> int:
    existing = load_manifest()
    paths = tracked_fixtures()

    lines: list[str] = [
        "# tests/fixtures/MANIFEST.toml",
        "#",
        "# SHA-256 manifest of the GEMMA parity reference fixtures.",
        "# Auto-generated by scripts/regenerate_fixture_manifest.py.",
        "# Verify with scripts/check_fixture_manifest.py (pre-commit hook).",
        "#",
        "# To intentionally update: regenerate fixtures, run the regenerate",
        "# script, commit MANIFEST.toml together with the new fixture files.",
        "",
    ]

    for path in paths:
        rel = path.relative_to(REPO_ROOT).as_posix()
        sha = sha256_of(path)
        meta = _extract_gemma_metadata(path)
        # Preserve hand-curated metadata from a previous manifest entry.
        prev = existing.get(rel, {})
        for k in ("gemma_version", "generation_cmd"):
            if k in prev and k not in meta:
                meta[k] = prev[k]

        lines.append(f'[file."{_toml_escape(rel)}"]')
        lines.append(f'sha256 = "{sha}"')
        for k, v in sorted(meta.items()):
            lines.append(f'{k} = "{_toml_escape(v)}"')
        lines.append("")

    FIXTURES_DIR.mkdir(parents=True, exist_ok=True)
    MANIFEST_PATH.write_text("\n".join(lines))
    print(
        f"Wrote {MANIFEST_PATH.relative_to(REPO_ROOT)} "
        f"with {len(paths)} fixture entries."
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
