{% set version = "1.5.0" %}

package:
  name: jamma
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/jamma/jamma-{{ version }}.tar.gz
  sha256: PLACEHOLDER

build:
  noarch: python
  number: 0
  entry_points:
    - jamma = jamma.cli:app
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  run_exports:
    - {{ pin_subpackage('jamma', max_pin='x.x') }}

requirements:
  host:
    - python >=3.11
    - pip
    - hatchling
  run:
    - python >=3.11
    - bed-reader >=1.0.0
    - jax >=0.8.0
    - jaxlib >=0.8.0
    - jaxtyping >=0.2.28
    - numpy >=1.26.0
    - psutil >=5.9.0
    - threadpoolctl >=3.0.0
    - typer >=0.12.0
    - loguru >=0.7.0
    - progressbar2 >=4.2.0

test:
  imports:
    - jamma
  commands:
    - jamma --help

about:
  home: https://github.com/michael-denyer/jamma
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: "JAMMA: JAX-Accelerated Mixed Model Association for GWAS"
  description: |
    Fast Python reimplementation of GEMMA for genome-wide association studies.
    JAX-accelerated with exact numerical equivalence to GEMMA at 200k sample scale.
  dev_url: https://github.com/michael-denyer/jamma

extra:
  recipe-maintainers:
    - michael-denyer
